name: SonarQube Analysis

on:
  push:
    branches:
      - develop  # Change if needed

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://13.203.193.239:9000"
          SONAR_PROJECT_KEY: "django-on-ec2"

      - name: Create GitHub Issue for New Errors
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.SONAR_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title": "New SonarQube Issues", "body": "Check SonarQube for new issues: http://13.203.193.239:9000/dashboard?id=django-on-ec2"}' \
            https://api.github.com/repos/mh-shanthipriya/django-on-ec2/issues
